application:
  title: Payments
  version: 1.0

spring:
  profiles:
    active: '@activeProfile@'
  application:
    name: payment-microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: ${DB_USERNAME:tech}
    password: ${DB_PASSWORD:tech_passwd}
  jpa:
    properties:
      hibernate:
        default_schema: payments
        enable_lazy_load_no_trans: true
    show-sql: true
  flyway:
    schemas: payments

server:
  servlet:
    context-path: /api
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
  path: swagger-ui-custom.html

feign:
  client:
    mercado-pago:
      url: https://api.mercadopago.com

mercado-pago:
  access-token: ${MP_ACCESS_TOKEN:APP_USR-1280609204491025-110319-0ef38ce64565a1827397a0d8f027da22-2076431474}
  notification-url: ${MP_NOTIFICATION_URL:https://46d2-2804-7f0-9382-1dd9-298c-add4-fac7-c73c.ngrok-free.app/api/payments/confirmation}

aws:
  sqs:
    payment-requests-queue: payment-requests-queue
  sns:
    updates-payments-topic: updates-payments-topic
