spring:
  datasource:
    url: jdbc:redshift://payment-cluster.c0r9joara2yt.us-east-1.redshift.amazonaws.com:5439/payments
  jpa:
    show-sql: true


mercadopago:
  access_token: ${MP_ACCESS_TOKEN:TEST-2194493215547460-072323-e7020fc0d11389fdae3dc86c6b9a1e4f-115466963}
  notification_url: ${MP_NOTIFICATION_URL:https://614f-2804-7f0-bec0-2fa7-4d18-dc53-6657-d0ff.ngrok-free.app/pagamentos/pedidos/notifications}
