spring:
  datasource:
    url: jdbc:redshift://payment-cluster.c0r9joara2yt.us-east-1.redshift.amazonaws.com:5439/payments
  jpa:
    show-sql: true

aws:
  sqs:
    payment-requests-queue: payment-requests-queue
  sns:
    updates-payments-topic: updates-payments-topic
