spring:
  datasource:
    url: jdbc:redshift://payment-cluster.c0r9joara2yt.us-east-1.redshift.amazonaws.com:5439/payments
  jpa:
    show-sql: true


mercadopago:
  access_token: ${MP_ACCESS_TOKEN}
  notification_url: ${MP_NOTIFICATION_URL}
